package view;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private int etapa = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConsultarPessoas = new javax.swing.JButton();
        jLabel_pessoa = new javax.swing.JLabel();
        btnSalasDoEvento = new javax.swing.JButton();
        btnEspacosDeCafe = new javax.swing.JButton();
        jLabel_edc = new javax.swing.JLabel();
        btnPessoas = new javax.swing.JButton();
        btnConsultarEspacosDeCafe = new javax.swing.JButton();
        btnConsultarSalasDeEvento = new javax.swing.JButton();
        jLabel_pessoa1 = new javax.swing.JLabel();
        jLabel_sde1 = new javax.swing.JLabel();
        jLabel_edc1 = new javax.swing.JLabel();
        jLabel_sde2 = new javax.swing.JLabel();
        btnTrocarEtapa = new javax.swing.JButton();
        lblEtapa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnConsultarPessoas.setText("Consultar");
        btnConsultarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPessoasActionPerformed(evt);
            }
        });

        jLabel_pessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_pessoa.setText("Pessoas");

        btnSalasDoEvento.setText("Cadastrar");
        btnSalasDoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasDoEventoActionPerformed(evt);
            }
        });

        btnEspacosDeCafe.setText("Cadastrar");
        btnEspacosDeCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspacosDeCafeActionPerformed(evt);
            }
        });

        jLabel_edc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_edc.setText("Espaços de Café");

        btnPessoas.setText("Cadastrar");
        btnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoasActionPerformed(evt);
            }
        });

        btnConsultarEspacosDeCafe.setText("Consultar");
        btnConsultarEspacosDeCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEspacosDeCafeActionPerformed(evt);
            }
        });

        btnConsultarSalasDeEvento.setText("Consultar");
        btnConsultarSalasDeEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSalasDeEventoActionPerformed(evt);
            }
        });

        jLabel_pessoa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_pessoa1.setText("Pessoas");

        jLabel_sde1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_sde1.setText("Salas de Evento");

        jLabel_edc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_edc1.setText("Espaços de Café");

        jLabel_sde2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_sde2.setText("Salas de Evento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_pessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_pessoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_sde1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarSalasDeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalasDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sde2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConsultarEspacosDeCafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_edc1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEspacosDeCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_edc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_edc)
                    .addComponent(jLabel_pessoa)
                    .addComponent(jLabel_sde2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalasDoEvento)
                    .addComponent(btnEspacosDeCafe)
                    .addComponent(btnPessoas))
                .addGap(18, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pessoa1)
                    .addComponent(jLabel_sde1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_edc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarPessoas)
                    .addComponent(btnConsultarSalasDeEvento)
                    .addComponent(btnConsultarEspacosDeCafe))
                .addGap(35, 35, 35))
        );

        btnTrocarEtapa.setText("Etapa: ");
        btnTrocarEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarEtapaActionPerformed(evt);
            }
        });

        lblEtapa.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnTrocarEtapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEtapa)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrocarEtapa)
                    .addComponent(lblEtapa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação do botão ConsultarSalasDeEvento
     *
     * @return
     */
    private void btnConsultarSalasDeEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSalasDeEventoActionPerformed
        // TODO add your handling code here:
        ConsultarSalasDeEvento myFrame = new ConsultarSalasDeEvento();
        myFrame.setVisible(true);
    }//GEN-LAST:event_btnConsultarSalasDeEventoActionPerformed

    /**
     * Ação do botão ConsultarEspacosDeCafe
     *
     * @return
     */
    private void btnConsultarEspacosDeCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEspacosDeCafeActionPerformed
        // TODO add your handling code here:
        ConsultarEspacosDeCafe myFrame = new ConsultarEspacosDeCafe();
        myFrame.setVisible(true);
    }//GEN-LAST:event_btnConsultarEspacosDeCafeActionPerformed

    /**
     * Ação do botão Pessoas
     *
     * @return
     */
    private void btnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoasActionPerformed
        // TODO add your handling code here:
        CadastrarPessoas myFrame = new CadastrarPessoas(etapa);
        myFrame.setVisible(true);
    }//GEN-LAST:event_btnPessoasActionPerformed

    /**
     * Ação do botão EspacosDeCafeAction
     *
     * @return
     */
    private void btnEspacosDeCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspacosDeCafeActionPerformed
        // TODO add your handling code here:
        CadastrarEspacosDeCafe myFrame = new CadastrarEspacosDeCafe();
        myFrame.setVisible(true);
    }//GEN-LAST:event_btnEspacosDeCafeActionPerformed

    /**
     * Ação do botão SalasDoEvento
     *
     * @return
     */
    private void btnSalasDoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasDoEventoActionPerformed
        // TODO add your handling code here:
        CadastrarSalasDeEvento myFrame = new CadastrarSalasDeEvento();
        myFrame.setVisible(true);
    }//GEN-LAST:event_btnSalasDoEventoActionPerformed

    /**
     * Ação do botão ConsultarPessoas
     *
     * @return
     */
    private void btnConsultarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPessoasActionPerformed
        // TODO add your handling code here:
        ConsultarPessoas myFrame = new ConsultarPessoas();
        myFrame.setVisible(true);
    }//GEN-LAST:event_btnConsultarPessoasActionPerformed

    /**
     * Ação do botão TrocarEtapa
     *
     * @return
     */
    private void btnTrocarEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarEtapaActionPerformed
        // TODO add your handling code here:
        etapa = etapa == 1 ? 2 : 1;
        lblEtapa.setText(String.valueOf(etapa));
    }//GEN-LAST:event_btnTrocarEtapaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarEspacosDeCafe;
    private javax.swing.JButton btnConsultarPessoas;
    private javax.swing.JButton btnConsultarSalasDeEvento;
    private javax.swing.JButton btnEspacosDeCafe;
    private javax.swing.JButton btnPessoas;
    private javax.swing.JButton btnSalasDoEvento;
    private javax.swing.JButton btnTrocarEtapa;
    private javax.swing.JLabel jLabel_edc;
    private javax.swing.JLabel jLabel_edc1;
    private javax.swing.JLabel jLabel_pessoa;
    private javax.swing.JLabel jLabel_pessoa1;
    private javax.swing.JLabel jLabel_sde1;
    private javax.swing.JLabel jLabel_sde2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEtapa;
    // End of variables declaration//GEN-END:variables
}
